project:
  type: book
  output-dir: docs
  

book:
  title: "R Learning"
  author: "Xuemei Chen"
  #date: "11/27/2023"
  navbar:
    search: true
  chapters:
    - index.qmd
    - intro.qmd
    - stats.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



